apiVersion: v1
kind: Pod
metadata:
  name: jira
  labels:
    name: jira
    environment: prod
    website: jira.dx-innovations.com
spec:
  containers:
    - image: eu.gcr.io/seoviu-web/jira:e74930c87d67b86177967354220db702d1f69350
      name: atlassian-jira-software
      ports:
        - containerPort: 8080
          name: jira
      resources:
        limits:
          memory: "5000Mi"
          cpu: "600m"
      volumeMounts:
          # name must match the volume name below
        - name: jira-persistent-storage-var
          # mount path within the container
          mountPath: /var/atlassian/jira
  volumes:
    - name: jira-persistent-storage-var
      gcePersistentDisk:
        # This GCE PD must already exist.
        pdName: jira-disk-1
        fsType: ext4
