apiVersion: v1
kind: Service
metadata:
  name: jirafrontend
  labels:
    app: jirafrontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    website: jira.dx-innovations.de
    environment: prod
